package server

var USERNAMES = [...]string{
	"Butterflyonrose",
	"yourea lion",
	"Macho_Moron",
	"Open Book",
	"Romeo",
	"Text Masters",
	"Miss Kick",
	"pokemon pie",
	"Cheered No",
	"Connect Tech",
	"Sweet sparrow",
	"Class Tribe",
	"Angel Girl",
	"Innocent- heart",
	"Basementfox",
	"FixLoven",
	"IntradouchingMyshelf",
	"Quest Pirates",
	"Happiness all around",
	"PlantedBrain Cheesy",
	"lolly",
	"Dishy Dudes",
	"Bean Never Seen",
	"Yaniv Ganzi",
	"TEH CATFACE",
	"Bee",
	"Pokie",
	"Rooster",
	"Greedy Foodies",
	"Angel candy",
	"Honey bean Angel",
	"GawdOfROFLS",
	"Tech Warriors",
	"WarlockOPain",
	"Power Mongers",
	"Alien",
	"Cheesy Nible",
	"printer",
	"Ice Geek",
	"The Breezers",
	"Skull Crusher",
	"SuperMagnificentExtreme",
	"HockeyWain",
	"Candy Cane",
	"Capitalist Crew",
	"Griller",
	"Smiling Face",
	"death heaven",
	"Bull dogs",
	"TallButShort",
	"Butterscotch",
	"Schooled In Success",
	"Slayer Trucker",
	"Barracudas",
	"Lovely Creamy",
	"1thousand is super fantastic",
	"AdamleKunning",
	"No Bean Left Behind",
	"pinkv0dka",
	"Bun Bun",
	"Hot Userame Here",
	"America",
	"TwinkleTwinkle",
	"Chillwildlife",
	"ExpertLuxLuv",
	"The Proud Linguist",
	"The Talent Pool",
	"Moon Down",
	"Dream Makers",
	"Bang Army",
	"have faith angel",
	"Promo Punch",
	"Smiley Doll",
	"Rosanna",
	"bae",
	"Poetic Divas",
	"cutiepie",
	"mustche",
	"Lesson Sessions",
	"Fred Creep",
	"peap0ds",
	"Love Pink",
	"Swing Shine",
	"sparkly",
	"Glowing",
	"twilightvanillagalaxies",
	"Muro45",
	"IwasReloading",
	"Classical John",
	"LittleMissPiggy",
	"Honey Bell",
	"Priceless Brains",
	"qwert",
	"Starry",
	"Electric Player",
	"Genius General",
	"Space Walker",
	"Maniac Messengers",
	"Lessons Learned",
	"Tango Tree",
	"Nible Improved",
	"Bronze Gamer Ghost",
	"Honey claudia colombian",
	"Honey bear Pearls",
	"Angel Sweetie",
	"lets run away to yesterday",
	"Crazy Eights",
	"Married Man",
	"Superior Start",
	"diamondhand146",
	"Twinkle Night",
	"Crunchy Crunch",
	"Internet Monster",
	"takenbyWine",
	"Stingers",
	"hearthacker",
	"unic0rntaking0ver",
	"Five Star Students",
	"crimson pain",
	"Geekish-God",
	"Eifersu",
	"Uncialgboy489",
	"Rainbow Doll",
	"Annihilators",
	"Cutlet",
	"President Punch",
	"Gamer",
	"Starry Angel",
	"Eagle Eye Roller",
	"DivinityV2",
	"Catchy Nails",
	"Lord-voldemort",
	"Circus Brain",
	"Tigger",
	"FreedomCostsTax",
	"Princess Point",
	"Criss cross",
	"Rumor Ring Viral",
	"Emerald Princess",
	"Grey Model",
	"Super Nigga",
	"hotTackleboxforgivingyouLittle",
	"Passion Entrepreneurs",
	"School Of Scholars",
	"Prometheus",
	"Chan14551",
	"AwayDolly",
	"BrideOlive",
	"sparkling lace",
	"Meaghan",
}
